# Generated by Django 5.1.4 on 2025-01-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('password_salt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('phone_model', models.CharField(max_length=255)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('year_of_presentation', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'phone_model'), name='unique_phone_contraint')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_descritption', models.CharField(max_length=300)),
                ('positive_summary', models.CharField(max_length=40)),
                ('negative_summary', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_review.phone')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_review.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'phone'), name='unique_review_constraint')],
            },
        ),
    ]
